apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: secret-operator
  namespace: flux-system
spec:
  interval: 1h
  url: https://repo.stackable.tech/repository/helm-dev/
  type: https
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secret-operator
  namespace: stble-operators
spec:
  interval: 6h
  releaseName: secret-operator
  targetNamespace: stble-operators
  install:
    createNamespace: true
  chart:
    spec:
      chart: secret-operator
      version: 0.0.0-dev
      interval: 6h
      sourceRef:
        kind: HelmRepository
        name: secret-operator
  values:
    networkPolicy:
      enabled: true