# Default values for secret-operator.
---
image:
  pullSecrets: []

externalProvisioner:
  image:
    repository: oci.stackable.tech/sdp/sig-storage/csi-provisioner
    tag: v5.3.0
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi
nodeDriverRegistrar:
  image:
    repository: oci.stackable.tech/sdp/sig-storage/csi-node-driver-registrar
    tag: v2.13.0
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi

secretOperator:
  image:
    repository: oci.stackable.tech/sdp/secret-operator
    # tag: 0.0.0-dev
    pullPolicy: IfNotPresent
  # Resources of the secret-operator container itself
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  securityContext:
    # secret-operator requires root permissions
    runAsUser: 0
    # It is strongly recommended to run secret-operator as a privileged container, since
    # it enables additional protections for the secret contents.
    # Unprivileged mode is EXPERIMENTAL and requires manual migration for an existing cluster.
    privileged: true
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

# Provide additional labels which get attached to all deployed resources
labels:
  stackable.tech/vendor: Stackable

podSecurityContext: {}
  # fsGroup: 2000

nodeSelector: {}

tolerations: []

affinity: {}

# priorityClassName: ...

# When running on a non-default Kubernetes cluster domain, the cluster domain can be configured here.
# See the https://docs.stackable.tech/home/stable/guides/kubernetes-cluster-domain guide for details.
# kubernetesClusterDomain: my-cluster.local

# Kubelet dir may vary in environments such as microk8s, see https://github.com/stackabletech/secret-operator/issues/229
kubeletDir: /var/lib/kubelet

secretClasses:
  tls:
    # The namespace that the TLS Certificate Authority is installed into.
    # Defaults to the namespace where secret-op is installed.
    caSecretNamespace: null

# See all available options and detailed explanations about the concept here:
# https://docs.stackable.tech/home/stable/concepts/telemetry/
telemetry:
  consoleLog:
    enabled: true
  fileLog:
    enabled: false
    rotationPeriod: hourly
    maxFiles: 6
  otelLogExporter:
    enabled: false
  otelTraceExporter:
    enabled: false
