---
apiVersion: v1
data: {}
kind: ConfigMap
metadata:
  name: secret-operator-configmap
  labels:
    app.kubernetes.io/name: secret-operator
    app.kubernetes.io/instance: secret-operator
    app.kubernetes.io/version: "0.6.0"
