---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: secret-operator-daemonset
  labels:
    app.kubernetes.io/name: secret-operator
    app.kubernetes.io/instance: secret-operator
    app.kubernetes.io/version: "0.5.0-nightly"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: secret-operator
      app.kubernetes.io/instance: secret-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: secret-operator
        app.kubernetes.io/instance: secret-operator
    spec:
      serviceAccountName: secret-operator-serviceaccount
      securityContext: {}
      containers:
        - name: secret-operator
          securityContext:
            privileged: true
            runAsUser: 0
          image: "docker.stackable.tech/stackable/secret-operator:0.5.0-nightly"
          imagePullPolicy: IfNotPresent
          resources: {}
          env:
            - name: CSI_ENDPOINT
              value: /csi/csi.sock
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: csi
              mountPath: /csi
            - name: mountpoint
              mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
        - name: external-provisioner
          image: k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0
          args:
            - --csi-address=/csi/csi.sock
            - --feature-gates=Topology=true
            - --extra-create-metadata
          volumeMounts:
            - name: csi
              mountPath: /csi
        - name: node-driver-registrar
          image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.4.0
          args:
            - --csi-address=/csi/csi.sock
            - --kubelet-registration-path=/var/lib/kubelet/plugins/secrets.stackable.tech/csi.sock
          volumeMounts:
            - name: registration-sock
              mountPath: /registration
            - name: csi
              mountPath: /csi
      volumes:
        - name: registration-sock
          hostPath:
            path: /var/lib/kubelet/plugins_registry/secrets.stackable.tech-reg.sock
        - name: csi
          hostPath:
            path: /var/lib/kubelet/plugins/secrets.stackable.tech/
        - name: mountpoint
          hostPath:
            path: /var/lib/kubelet/pods/
