apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ~/deploy/helm/secret-operator/crds/crds.yaml
  - ~/deploy/helm/secret-operator/Chart.yaml
  - ~/deploy/helm/secret-operator/values.yaml