---
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: tls
spec:
  backend: # <1>
    autoTls: # <2>
      ca:
        secret:
          name: secret-provisioner-tls-ca
          namespace: default
        autoGenerate: true
    # or... <1>
    k8sSearch: # <3>
      searchNamespace:
        pod: {}
        # or...
        name: my-namespace
      trustStoreConfigMapName: tls-ca # <4>
