---
apiVersion: secrets.stackable.tech/v1alpha2
kind: SecretClass
metadata:
  name: tls
spec:
  backend:
    certManager:
      issuer:
        kind: Issuer
        name: secret-operator-demonstration
      keyGeneration: # <1>
        rsa: # <2>
          length: 4096 # <3>
