[package]
name = "krb5-sys"
version = "0.1.0"
edition = "2021"
links = "krb5"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.59.2"
pkg-config = "0.3.24"
