---
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: tls-cert-manager # <1>
spec:
  backend:
    experimentalCertManager:
      issuer:
        kind: Issuer # <2>
        name: secret-operator-demonstration # <3>
