---
apiVersion: v1
kind: Pod
metadata:
  name: example-secret-consumer
spec:
  volumes:
  - name: tls
    ephemeral:
      volumeClaimTemplate:
        metadata:
          annotations:
            secrets.stackable.tech/class: secret
            secrets.stackable.tech/scope: node,pod,service=secret-consumer-nginx
        spec:
          storageClassName: secrets.stackable.tech
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: "1"
  containers:
  - name: ubuntu
    image: ubuntu
    stdin: true
    tty: true
    volumeMounts:
    - name: tls
      mountPath: /tls
