---
apiVersion: v1
kind: Pod
metadata:
  name: example-secret-consumer
spec:
  volumes:
  - name: secret
    ephemeral:
      volumeClaimTemplate:
        metadata:
          annotations:
            secrets.stackable.tech/class: secret # <1>
            secrets.stackable.tech/scope: node # <2>
        spec:
          storageClassName: secrets.stackable.tech # <3>
          accessModes: # <4>
          - ReadWriteOnce
          resources: # <4>
            requests:
              storage: "1"
  containers:
  - name: ubuntu
    volumeMounts:
    - name: tls # <5>
      mountPath: /tls
