---
apiVersion: v1
kind: Pod
metadata:
  name: example-secret-consumer
spec:
  volumes:
  - name: secret
    csi:
      driver: secrets.stackable.tech # <1>
      volumeAttributes:
        secrets.stackable.tech/class: tls # <2>
        secrets.stackable.tech/scope: node,pod,service=secret-consumer # <3>
  containers:
  - name: ubuntu
    volumeMounts:
    - name: tls # <4>
      mountPath: /tls
