---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "operator.fullname" . }}-csi-node-driver
  labels:
    {{- include "operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        internal.stackable.tech/image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        {{- with .Values.csiNodeDriver.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      # NOTE (@Techassi): Does it maybe make sense to have two different service accounts?
      serviceAccountName: {{ include "operator.fullname" . }}-serviceaccount
      securityContext:
        {{- toYaml .Values.csiNodeDriver.podSecurityContext | nindent 8 }}
      containers:
        - name: csi-node-service
          securityContext:
            {{- toYaml .Values.csiNodeDriver.nodeService.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{ .Values.csiNodeDriver.nodeService.resources | toYaml | nindent 12 }}
          # The arguments passed to the command being run in the container. The final command will
          # look like `secret-operator run csi-server [OPTIONS]`. The CSI server needs to run on
          # every Kubernetes cluster node and as such is deployed as a DaemonSet.
          args:
            - run
            - csi-node-service
          env:
            # The following env vars are passed as clap (think CLI) arguments to the operator.
            # They are picked up by clap using the structs defied in the operator.
            # (which is turn pulls in https://github.com/stackabletech/operator-rs/blob/main/crates/stackable-operator/src/cli.rs)
            # You can read there about the expected values and purposes.

            - name: CSI_ENDPOINT
              value: /csi/csi.sock
            - name: PRIVILEGED
              value: {{ .Values.csiNodeDriver.nodeService.securityContext.privileged | quote }}

            # Sometimes products need to know the operator image, e.g. the opa-bundle-builder OPA
            # sidecar uses the operator image.
            - name: OPERATOR_IMAGE
              # Tilt can use annotations as image paths, but not env variables
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['internal.stackable.tech/image']

            # Namespace the operator Pod is running in, e.g. used to construct the conversion
            # webhook endpoint.
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            # The name of the Kubernetes Service that point to the operator Pod, e.g. used to
            # construct the conversion webhook endpoint.
            - name: OPERATOR_SERVICE_NAME
              value: {{ include "operator.fullname" . }}

            # Operators need to know the node name they are running on, to e.g. discover the
            # Kubernetes domain name from the kubelet API.
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

            # The namespace that the TLS Certificate Authority is installed into.
            # Internally defaults to the namespace where secret-operator is installed.
            {{- if .Values.secretClasses.tls.caSecretNamespace }}
            - name: TLS_SECRETCLASS_CA_SECRET_NAMESPACE
              value: {{ .Values.secretClasses.tls.caSecretNamespace }}
            {{- end }}

            {{- if .Values.kubernetesClusterDomain }}
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: {{ .Values.kubernetesClusterDomain | quote }}
            {{- end }}
            {{- include "telemetry.envVars" . | nindent 12 }}
          volumeMounts:
            - name: csi
              mountPath: /csi
            - name: mountpoint
              mountPath: {{ .Values.csiNodeDriver.kubeletDir }}/pods
              {{- if .Values.csiNodeDriver.nodeService.securityContext.privileged }}
              mountPropagation: Bidirectional
              {{- end }}
            - name: tmp
              mountPath: /tmp

        - name: external-provisioner
          image: "{{ .Values.csiNodeDriver.externalProvisioner.image.repository }}:{{ .Values.csiNodeDriver.externalProvisioner.image.tag }}"
          imagePullPolicy: {{ .Values.csiNodeDriver.externalProvisioner.image.pullPolicy }}
          resources:
            {{ .Values.csiNodeDriver.externalProvisioner.resources | toYaml | nindent 12 }}
          args:
            - --csi-address=/csi/csi.sock
            - --feature-gates=Topology=true
            - --extra-create-metadata
          volumeMounts:
            - name: csi
              mountPath: /csi

        - name: node-driver-registrar
          image: "{{ .Values.csiNodeDriver.nodeDriverRegistrar.image.repository }}:{{ .Values.csiNodeDriver.nodeDriverRegistrar.image.tag }}"
          imagePullPolicy: {{ .Values.csiNodeDriver.nodeDriverRegistrar.image.pullPolicy }}
          resources:
            {{ .Values.csiNodeDriver.nodeDriverRegistrar.resources | toYaml | nindent 12 }}
          args:
            - --csi-address=/csi/csi.sock
            - --kubelet-registration-path={{ .Values.csiNodeDriver.kubeletDir }}/plugins/secrets.stackable.tech/csi.sock
          volumeMounts:
            - name: registration-sock
              mountPath: /registration
            - name: csi
              mountPath: /csi
      volumes:
        - name: registration-sock
          hostPath:
            # node-driver-registrar appends a driver-unique filename to this path to avoid conflicts
            # see https://github.com/stackabletech/secret-operator/issues/229 for why this path should not be too long
            path: {{ .Values.csiNodeDriver.kubeletDir }}/plugins_registry
        - name: csi
          hostPath:
            path: {{ .Values.csiNodeDriver.kubeletDir }}/plugins/secrets.stackable.tech/
        - name: mountpoint
          hostPath:
            path: {{ .Values.csiNodeDriver.kubeletDir }}/pods/
        - name: tmp
          emptyDir: {}
      {{- with .Values.csiNodeDriver.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.csiNodeDriver.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.csiNodeDriver.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.csiNodeDriver.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
