---
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: tls
  labels:
  {{- include "operator.labels" . | nindent 4 }}
spec:
  backend:
    autoTls:
      ca:
        secret:
          name: secret-provisioner-tls-ca
          namespace: {{ .Values.secretClasses.tls.caSecretNamespace | default .Release.Namespace }}
        autoGenerate: true
