[package]
name = "krb5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
krb5-sys = { version = "0.1.0", path = "../krb5-sys" }
snafu = "0.7.0"
tempfile = "3.3.0"
