= Scope

Secrets often cover some specific aspect of a workload. For example:

* A Kerberos credential may be bound to one node IP
* An internal TLS certificate's `subjectAlternateName` section must match the `Pod` object's name and service

To solve this, the Stackable Secret Operator has a concept of "scopes", which allow a xref:volume.adoc[] to selectively
include this extra context. The exact effect of the scope depends on which xref:secretclass.adoc#backend[`backend`] is used.

[#node]
== `node`

The `node` scope is resolved to the name of the Kubernetes `Node` object that the `Pod` is running on. This will typically
be the DNS name of the node.

[#pod]
== `pod`

The `pod` scope is resolved to the name of the Kubernetes `Pod`. This allows the secret to differentiate between `StatefulSet` replicas.

[#service]
== `service`

The `service` scope allows `Pod` objects to specify custom scopes. This should typically correspond to `Service` objects that the
`Pod` participate in.


== Examples
Below are a few examples that may help better illustrate the concept of a secret scope:

So a secret provided by the autoTls provider that is configured with the scopes `node` and `pod` would get the following values added to the `subjectAlternateName` extension field:

 - Node IP Address
 - Node DNS Name
 - Pod DNS Names

By also specifying the service scope it is possible to also add DNS names of `Service` objects that can be reached to the SAN extension.
