= `SecretClass`

A `SecretClass` is a cluster-global Kubernetes resource that defines a category of secrets that the Secret Operator knows how to provision.

This is intended to provide an abstraction between how the secret is used ("I need a certificate for my cluster's TLS PKI") and how
it is provisioned (automatically and generated by the operator's internal CA, provisioned by the cluster administrator, or provisioned by an
external service such as Hashicorp Vault).

A `SecretClass` looks like this:

[source,yaml]
----
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: tls
spec:
  backend: # <1>
    autoTls: # <2>
      ca:
        secret:
          name: secret-provisioner-tls-ca
          namespace: default
    # or... <1>
    k8sSearch: # <3>
      searchNamespace:
        pod: {}
        # or...
        name: my-namespace
      secretLabels:
        type: custom-secret
----
<1> Only one backend is supported
<2> Configures and selects the xref:#backend-autotls[] backend
<3> Configures and selects the xref:#backend-k8ssearch[] backend

[#backends]
== Backends

Each `SecretClass` is a associated with a single backend, which dictates the mechanism for issuing that kind of secret.

[#backend-autotls]
=== `autoTls`

*Format*: xref:#format-tls[]

Issues a TLS certificate signed by the Secret-Operator. The claims contained in the certificate depend on which
xref:./scope.adoc[scopes] are specified on the `Volume`.

==== Reference

[source,yaml]
----
autoTls:
  ca:
    secret:
      name: secret-provisioner-tls-ca
      namespace: default
----

`autoTls.ca.secret`:: A Kubernetes `Secret` object containing the Certificate Authority private key and certificate. Will be created when the
first certificate is issued if it does not already exist.

[#backend-k8ssearch]
=== `k8sSearch`

*Format*: Free-form

A Kubernetes `Secret` object is selected based on the xref:./scope.adoc[scopes] specified on the `Volume`. Each field in this `Secret` is mapped
to one file. It is suggested this secret should follow one of the xref:#formats[formats defined in this document].

[#formats]
== Formats

Each backend should conform to at least one common format. This is intended to allow cluster operators to switch between interoperable backends with
minimal impact on secret consumers.

[#format-tls]
=== TLS

The secret contains the following files:

`ca.crt`:: The certificate of the Certificate Authority (and associated chain) that has signed the certificate, in the PEM format.
`tls.crt`:: The certificate identifying the `Pod`, in the PEM format.
`tls.key`:: The private key corresponding to `tls.crt`, in the PEM format.
