# FROM ubuntu:20.04
# RUN apt-get update && apt-get install --yes krb5-kdc krb5-admin-server

FROM docker.io/library/alpine@sha256:ceeae2849a425ef1a7e591d8288f1a58cdf1f4e8d9da7510e29ea829e61cf512
RUN apk add krb5 krb5-server
