apiVersion: v1
kind: ConfigMap
metadata:
  name: secret-operator-deployer-manifests
data:
  csidriver.yaml: |
    apiVersion: storage.k8s.io/v1
    kind: CSIDriver
    metadata:
      name: secrets.stackable.tech
    spec:
      attachRequired: false
      podInfoOnMount: true
      fsGroupPolicy: File
      volumeLifecycleModes:
        - Ephemeral
        - Persistent
  storageclass.yaml: |
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: secrets.stackable.tech
    provisioner: secrets.stackable.tech
  daemonset.yaml: |
    apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      labels:
        app.kubernetes.io/instance: secret-operator
        app.kubernetes.io/name: secret-operator
        app.kubernetes.io/version: 23.1.0
      name: secret-operator-daemonset
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/instance: secret-operator
          app.kubernetes.io/name: secret-operator
      template:
        metadata:
          creationTimestamp: null
          labels:
            app.kubernetes.io/instance: secret-operator
            app.kubernetes.io/name: secret-operator
        spec:
          containers:
          - name: secret-operator
            env:
            - name: CSI_ENDPOINT
              value: /csi/csi.sock
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            image: docker.stackable.tech/stackable/secret-operator:23.1.0
            imagePullPolicy: IfNotPresent
            securityContext:
              privileged: true
              runAsUser: 0
            volumeMounts:
            - mountPath: /csi
              name: csi
            - mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
              name: mountpoint
          - name: external-provisioner
            args:
            - --csi-address=/csi/csi.sock
            - --feature-gates=Topology=true
            - --extra-create-metadata
            image: k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - mountPath: /csi
              name: csi
          - name: node-driver-registrar
            args:
            - --csi-address=/csi/csi.sock
            - --kubelet-registration-path=/var/lib/kubelet/plugins/secrets.stackable.tech/csi.sock
            image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.4.0
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - mountPath: /registration
              name: registration-sock
            - mountPath: /csi
              name: csi
          serviceAccount: secret-operator-serviceaccount
          serviceAccountName: secret-operator-serviceaccount
          volumes:
          - hostPath:
              path: /var/lib/kubelet/plugins_registry/secrets.stackable.tech-reg.sock
              type: ""
            name: registration-sock
          - hostPath:
              path: /var/lib/kubelet/plugins/secrets.stackable.tech/
              type: ""
            name: csi
          - hostPath:
              path: /var/lib/kubelet/pods/
              type: ""
            name: mountpoint
