= Cert-Manager integration
:description: Integrate Cert-Manager with Stackable Secret Operator to manage certificates. Follow steps for configuration, creating SecretClass, and using certificates in Pods.
:cert-manager: https://cert-manager.io/
:letsencrypt: https://letsencrypt.org/

NOTE: The Cert-Manager backend was marked as non-experimental in SDP 25.11.0

{cert-manager}[Cert-Manager] is a common tool to manage certificates in Kubernetes, especially when backed by an external Certificate Authority (CA) such as {letsencrypt}[Let\'s Encrypt].

The Stackable Secret Operator supports requesting certificates from Cert-Manager.

[#caveats]
== Caveats

Cert-Manager is designed to manage relatively long-lived certificates that are stored in Kubernetes Secrets.
By contrast, the Stackable Secret Operator is designed to generate temporary short-lived certificates.

This has a couple of repercussions:

* Longer-lived certificates mean that a leaked certificate has potential to be abused for longer.
* Application teams may have access to read Secrets in their respective applications' Namespaces.

Where possible, it is recommended using the xref:secretclass.adoc#backend-autotls[`autoTls` backend] instead.

[#issuer]
== Configuring Cert-Manager

NOTE: Using the xref:secretclass.adoc#backend-autotls[`autoTls` backend] instead for self-signed PKIs is recommended.
The Cert-Manager's CA issuer is used in these examples to illustrate the broader concepts.

To do this, you will first need to teach Cert-Manager how to create your certificates.

In a production setup this will likely use an external CA such as ACME or OpenBao/Vault.
However, to make this guide self-contained, Cert-Manager will create a self-signed CA certificate instead.

[source,yaml]
----
include::example$cert-manager/issuer.yaml[]
----
<1> This is the Issuer that our created certificates will reference later

[#secretclass]
== Creating a SecretClass

The Stackable Secret Operator needs to know how to request the certificates from Cert-Manager.
Do this by creating a xref:secretclass.adoc[] using the xref:secretclass.adoc#backend-certmanager[`certManager` backend].

[source,yaml]
----
include::example$cert-manager/secretclass.yaml[]
----
<1> Both certificates and Pods will reference this name, to ensure that the correct certificates are found
<2> This guide uses a namespaced Issuer, rather than a cluster-scoped ClusterIssuer
<3> The Cert-Manager Issuer that should sign these certificates, as created xref:#issuer[before]

[#pod]
== Using the certificate

Finally, you can create and expose a Pod that requests and uses the certificate!

[source,yaml]
----
include::example$cert-manager/pod.yaml[]
----
<1> A secret xref:volume.adoc[volume] is created, where the certificate will be exposed to the app
<2> The volume references the SecretClass defined xref:#secretclass[before]
<3> The app requires the certificate to be valid for the scopes xref:scope.adoc#node[`node`] and xref:scope.adoc#service[`service=my-app`]
<4> nginx is configured to use the mounted certificate
<5> nginx is exposed as a Kubernetes Service
