= Scope
:description: Stackable Secret Operator supports scopes for secrets like node, pod, and service, adding context like IP, pod names, and DNS to credentials.

Secrets often cover some specific aspect of a workload.
For example:

* A Kerberos credential may be bound to one node IP.
* An internal TLS certificate's `subjectAlternateName` section must match the Pod object's name and service.

To solve this, the Stackable Secret Operator has a concept of "scopes", which allow a xref:volume.adoc[] to selectively include this extra context.
The exact effect of the scope depends on which xref:secretclass.adoc#backend[`backend`] is used.

== Supported Scopes

[#listener-volume]
=== `listener-volume`

*Syntax*: `listener-volume=<VOLUME>` (for example: `listener-volume=my-listener`)

The `listener-volume` scope is resolved according to a xref:listener-operator:listener.adoc[Listener].

The xref:listener-operator:listener.adoc[Listener] should be mounted as a xref:listener-operator:volume.adoc[volume] alongside the Secret volume, and takes the name of that
volume as its parameter. This way, the scope will automatically adapt to the xref:listener-operator:listenerclass.adoc[ListenerClass] that it uses.

Multiple xref:listener-operator:listener.adoc[Listener]s can be bound by specifying the scope multiple times.

note:: The parameter is the name of the Pod's _volume_, not the name of the PersistentVolumeClaim, PersistentVolume, or xref:listener-operator:listener.adoc[Listener]. This allows the scope to bind to replica-specific or ephemeral xref:listener-operator:listener.adoc[Listener]s.

[#pod]
=== `pod`

*Syntax*: `pod`

The `pod` scope is resolved to the name of the Kubernetes Pod.
This allows the secret to differentiate between StatefulSet replicas.

[#node]
=== `node`

*Syntax*: `node`

The `node` scope is resolved to the name of the Kubernetes Node object that the Pod is running on.
This will typically be the DNS name of the node.

NOTE: Consider using the xrerf:#listener-volume[] scope instead, which also allows the scope to automatically adjust to how the Pod is exposed.

[#service]
=== `service`

*Syntax*: `service=<SERVICE>` (for example: `service=my-service`)

The `service` scope is resolved to an arbitrary Kubernetes Service in the same Namespace.

NOTE: This scope only supports cluster-internal (`ClusterIP`) Services. Consider using the xref:#listener-volume[] scope instead.

== Example

For example, a TLS certificate provisioned by the xref:secretclass.adoc#backend-autotls[`autoTls`] backend, with the scopes
xref:#node[] and xref:#pod[] would contain the following values in its `subjectAlternateName` (SAN) extension field:

* The node's IP address
* The node's fully qualified domain name (`my-node.example.com`, without a trailing dot)
* The pod's fully qualified domain name (`my-pod.my-service.my-namespace.svc.cluster.local`, without a trailing dot)
