= Volume

The primary entry point for applications is by mounting a secret into a `Pod` object's `volume` set. This is done by using Kubernetes'
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#ephemeralvolumesource-v1-core[`EphemeralVolumeSource`] type.
For example:

[source,yaml]
----
include::example$volume-pod.yaml[]
----
<1> This secret is provided by the xref:secretclass.adoc[] named `tls`
<2> This secret should be xref:scope.adoc[scoped] by the intersection of xref:scope.adoc#node[`node`], xref:scope.adoc#pod[`pod`], and the xref:scope.adoc#service[`service`] named `secret-consumer`
<3> Tells Kubernetes that the Stackable Secret Operator is responsible for mounting this volume
<4> Kubernetes requires us to specify some boilerplate settings for a `PersistentVolumeClaim` to be well-formed
<5> The injected volume can then be mounted into a container, just like any other volume. In this example, the secrets are provided in the `/tls` directory of the container.

NOTE: Only ephemeral volumes are supported, the Secret Operator does *not* support declaring standalone `PersistentVolumeClaim` objects.

== Attributes

=== `secrets.stackable.tech/class`

*Required*: true

*Backends*: All

The name of the xref:secretclass.adoc[] that is responsible for providing this secret.

=== `secrets.stackable.tech/scope`

*Required*: false

*Default value*: no scopes

*Backends*: All

The xref:scope.adoc[scopes] used to select or provision the secret. Multiple scopes should be separated by commas (`,`), and scope parameters are separated by equals signs (`=`) where applicable.

[#volume-attr-format]
=== `secrets.stackable.tech/format`

*Required*: false

*Default value*: default format of backend

*Backends*: All

The xref:secretclass.adoc#format[format] that the secret should be written as.

This can be either the default output format of the xref:secretclass.adoc#backend[backend], or a format that it defines a conversion into.

=== `secrets.stackable.tech/autotls.cert.lifetime`

*Required*: false

*Default value*: `maxCertificateLifetime` set on the SecretClass

*Backends*: xref:secretclass.adoc#backend-autotls[]

The lifetime the created certificate should have.
Please note that you can not request a lifetime longer than allowed by `maxCertificateLifetime` on the SecretClass.
If you do so, `maxCertificateLifetime` will be used as the certificate lifetime, to adhere to the requirements
set by the admin that created the SecretClass.

=== `secrets.stackable.tech/kerberos.service.names`

*Required*: false

*Default value*: HTTP

*Backends*: xref:secretclass.adoc#backend-kerberoskeytab[]

The service names to be prepended to the provisioned principals. The provisioned principals will have the form `service/scope@realm`. Multiple service names should
be separated by commas (`,`).
