---
apiVersion: secrets.stackable.tech/v1alpha2
kind: SecretClass
metadata:
  name: tls
spec:
  backend:
    autoTls:
      ca:
        secret:
          name: secret-provisioner-tls-ca
          namespace: will-be-overridden-by-secret-operator
        autoGenerate: true
